### PR TITLE
Fixed single viewcontroller bug

### PR DESCRIPTION
**Pull request by kayvink**
- Prevents crash when there is only one view controller. 
- Centers the view controller

### CODE REVIEW

**Comment by kitasuke** [comment]
@kayvink Thanks for you PR!
The reason why it crashes is here.

```swift
    private func contentOffsetXForCurrentPage(#nextIndex: Int) -> CGFloat {
        let ratio = CGFloat(nextIndex) / CGFloat(menuItemViews.count - 1)
        println(ratio)
        let previousMenuItem = menuItemViews[currentPage]
        return (contentSize.width - frame.width) * ratio
    }
```

It's missing count value check before defining `ratio`, since zero should not be in denominator.
So, could you  revert your commit and implement zero count check?
Or I can fix it in case you don't know what to do.

**Comment by kayvink** [comment]
I know, I added added a condition that will prevent it to ever have to calculate the offset. If it is only one controller it should be centred right?

```Swift 
private func targetContentOffsetX(#nextIndex: Int) -> CGFloat {
        switch options.menuDisplayMode {
        case .FlexibleItemWidth(let centerItem, _):
            if !centerItem {
                return contentOffsetXForCurrentPage(nextIndex: nextIndex)
            }
            return centerOfScreenWidth(nextIndex: nextIndex)
        case .FixedItemWidth(_, let centerItem, _):
            if !centerItem && menuItemViews.count > 1{ // <-- Here
                return contentOffsetXForCurrentPage(nextIndex: nextIndex)
            }
            return centerOfScreenWidth(nextIndex: nextIndex)
        case .SegmentedControl:
            return contentOffset.x
        }
    }
```

Should probably add one for `.FlexibleItemWidth` as well. Or did you mean something else?

**Comment by kitasuke** [comment]
Well, I was thinking that centered position is right or not for only one controller earlier, but I think it should not be centered.
Although What you indicates is a good point, it's a different issue which is about how it handles x position of menu item view.

The reason of the crash has nothing to do with where it's presented. Programatically it's wrong that puts zero to denominator, so it should be fixed beside the issue above.

Does it make sense for you?

**Comment by kayvink** [comment]
I see what you mean, how else would you prevent this form happening then?

Also with the fix I proposed it works on the initial `viewDidLoad` it works, but when I return from another view in the `navigationController` it aligns the single controller to the left of the screen.

**Comment by kitasuke** [comment]
You can just check `menuItemViews.count` before calculation.
`minimumSupportedViewCount` should be declared in `PagingMenuOptions` as `let` constant.

```swift
private func contentOffsetXForCurrentPage(#nextIndex: Int) -> CGFloat {
    if menuItemViews.count == options.minimumSupportedViewCount {
        return 0.0
    }
    let ratio = CGFloat(nextIndex) / CGFloat(menuItemViews.count - 1)
    let previousMenuItem = menuItemViews[currentPage]
    return (contentSize.width - frame.width) * ratio
}
```

I'll check the behaviour and look into more detail later!

**Comment by kayvink** [comment]
Thanks for looking into it. I didn't choose to do that because it aligns the view controller to the left. Would there be another way to center it afterwards?

**Comment by kitasuke** [comment]
If you want to put it center, just set `centerItem = true`.

**Comment by kayvink** [comment]
I see, what confused me was the slidable menubar. 👍🏻

**Comment by kitasuke** [comment]
So everything is clean, right?
I'll fix a bug of single view controller usage with a different PR. I'll close this PR since your PR does not fix the bug it self.
Thanks!

**Comment by kayvink** [comment]
👍🏻

**Pull request closed without merging**
