### PR TITLE
Cut off iOS 8 support

### PR DESCRIPTION
**Pull request by kitasuke**
- [x] NSLayoutAnchor
- [x] Refactoring

### CODE REVIEW

**Comment by cezheng** [comment]
Seriously? Seem still over 15% percentage of the active devices are using iOS 8 or earlier as of May 2016

https://developer.apple.com/support/app-store/

**Comment by kitasuke** [comment]
This won't be merged soon.

**Comment by piv199** [comment]
iOS <8 is 3%
iOS 8 is currently 10% of devices

Why deprecating iOS 8?

**Comment by kitasuke** [comment]
This PR will be merged once iOS 10 is released.
This library supports only two major OSes, so iOS 8 won't be major one anymore around that time. You can still use older version of library to support iOS 8.

**Comment by piv199** [comment]
But if I move to swift 3, then I can't support iOS 8 anymore with this library?

**Comment by kitasuke** [comment]
I'll create iOS8 support branch in Swift 3, so you can use this library with the branch. However, it might not be maintained since master branch will support iOS 9+ and use Swift 3.

**Pull request merged**
